### PR TITLE
#8 added IGraphiteNameFormatter

### LINKED ISSUE #8: Template based format for graphite endpoint
Hi,
As graphite is limited in it's query capabilities, it'll be extremely valuable to control the metric name using template, like the first implementation: https://github.com/alhardy/AppMetrics.Extensions.Graphite/blob/c04dd30be4f012f7fa6b870b88d0b22e95803826/src/App.Metrics.Extensions.Reporting.Graphite/Client/GraphiteMetricNameFormatter.cs 

It allow us to create metrics using templates like this:
{type}.{tag:host}.{context}.{tag:route}.{nameWithUnit}.{tag:http_status_code}

### PR DESCRIPTION
**Pull request by nataly87s**
added IGraphiteNameFormatter to be able to change the way the name is formatted

Thanks for helping out :+1:

Before submitting a pull request, please have a quick read through the [contribution guidlines](https://github.com/alhardy/AppMetrics/blob/master/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`

### The issue or feature being addressed
closes #8 

### Details on the issue fix or feature implementation

- Created an IGraphiteNameFormatter interface, and a default implementation

### Confirm the following

- [X] I have ensured that I have merged the latest changes from the dev branch
- [X] I have successfully run a [local build](https://github.com/alhardy/AppMetrics#how-to-build)
- [ ] I have included unit tests for the issue/feature
- [X] I have included the github issue number in my commits

### CODE REVIEW

**Review by alhardy — CHANGES_REQUESTED** [review]
Awesome, looks good.

One thing though, I think the out-of-box Grafana dashboards need updating - see https://github.com/alhardy/AppMetrics.Extensions.Graphite/tree/dev/visualization/grafana-dashbaords

**Comment by nataly87s** [comment]
The default formatter is the same as it was before the changes I made, so the dashboards should stay the same

**Comment by alhardy** [comment]
Seems to be a slight difference breaking the dashboards, e.g.

`app.App_Metrics_Graphite_Sandbox.env.stage.server.DESKTOP-S95E939.meter.Application_HttpRequests.Error_Rate.Total 4 1498599189`

vs 

`app.App_Metrics_Graphite_Sandbox.env.stage.server.DESKTOP-S95E939.meter.Application.HttpRequests.Error_Rate.Total 4 1498599189`

If you don't get a chance today, I can merge the PR and make these changes (and add a unit test) tomorrow.

**Comment by nataly87s** [comment]
I updated the formatter so that it would be compatible with the previous version.
I tested the grafana dashboard locally (with Docker) and there's one panel that says "Unknown panel type: grafana-piechart-panel" but other than that it looks good now

**Comment by alhardy** [comment]
@nataly87s all looks good now, thanks! 

You'd need to install the [pie-chart panel](https://grafana.com/plugins/grafana-piechart-panel) to fix that issue

**Comment by alhardy** [comment]
@nataly87s updated package with your PR on nuget

**Pull request merged**
